version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=UPtZ5MeRvq  
    depends_on:
      - db

  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpass1234
      POSTGRES_DB: estoque
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
